// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	//	*AgentMessage_Stats
	Content       isAgentMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentMessage) GetContent() isAgentMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetStats() *StatsUpdate {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

type isAgentMessage_Content interface {
	isAgentMessage_Content()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type AgentMessage_Stats struct {
	Stats *StatsUpdate `protobuf:"bytes,4,opt,name=stats,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Content() {}

func (*AgentMessage_Result) isAgentMessage_Content() {}

func (*AgentMessage_Stats) isAgentMessage_Content() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsUpdate) Reset() {
	*x = StatsUpdate{}
	mi := &file_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsUpdate) ProtoMessage() {}

func (x *StatsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsUpdate.ProtoReflect.Descriptor instead.
func (*StatsUpdate) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatsUpdate) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StatsUpdate) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatsUpdate) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type PanelCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*PanelCommand_Create
	//	*PanelCommand_Start
	//	*PanelCommand_Stop
	//	*PanelCommand_Remove
	Action        isPanelCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelCommand) Reset() {
	*x = PanelCommand{}
	mi := &file_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelCommand) ProtoMessage() {}

func (x *PanelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelCommand.ProtoReflect.Descriptor instead.
func (*PanelCommand) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *PanelCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PanelCommand) GetAction() isPanelCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PanelCommand) GetCreate() *CreateContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *PanelCommand) GetStart() *StartContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *PanelCommand) GetStop() *StopContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *PanelCommand) GetRemove() *RemoveContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

type isPanelCommand_Action interface {
	isPanelCommand_Action()
}

type PanelCommand_Create struct {
	Create *CreateContainer `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type PanelCommand_Start struct {
	Start *StartContainer `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type PanelCommand_Stop struct {
	Stop *StopContainer `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type PanelCommand_Remove struct {
	Remove *RemoveContainer `protobuf:"bytes,5,opt,name=remove,proto3,oneof"`
}

func (*PanelCommand_Create) isPanelCommand_Action() {}

func (*PanelCommand_Start) isPanelCommand_Action() {}

func (*PanelCommand_Stop) isPanelCommand_Action() {}

func (*PanelCommand_Remove) isPanelCommand_Action() {}

type CreateContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainer) Reset() {
	*x = CreateContainer{}
	mi := &file_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainer) ProtoMessage() {}

func (x *CreateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainer.ProtoReflect.Descriptor instead.
func (*CreateContainer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *CreateContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type StartContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainer) Reset() {
	*x = StartContainer{}
	mi := &file_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainer) ProtoMessage() {}

func (x *StartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainer.ProtoReflect.Descriptor instead.
func (*StartContainer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *StartContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainer) Reset() {
	*x = StopContainer{}
	mi := &file_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainer) ProtoMessage() {}

func (x *StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainer.ProtoReflect.Descriptor instead.
func (*StopContainer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *StopContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainer) Reset() {
	*x = RemoveContainer{}
	mi := &file_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainer) ProtoMessage() {}

func (x *RemoveContainer) ProtoReflect() protoreflect.Message {
	mi := &file_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainer.ProtoReflect.Descriptor instead.
func (*RemoveContainer) Descriptor() ([]byte, []int) {
	return file_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_proto_agent_proto protoreflect.FileDescriptor

const file_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x11proto/agent.proto\x12\x04deft\"\xbd\x01\n" +
	"\fAgentMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\theartbeat\x18\x02 \x01(\v2\x0f.deft.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\x06result\x18\x03 \x01(\v2\x13.deft.CommandResultH\x00R\x06result\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x11.deft.StatsUpdateH\x00R\x05statsB\t\n" +
	"\acontent\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"b\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\vStatsUpdate\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\"\xf2\x01\n" +
	"\fPanelCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12/\n" +
	"\x06create\x18\x02 \x01(\v2\x15.deft.CreateContainerH\x00R\x06create\x12,\n" +
	"\x05start\x18\x03 \x01(\v2\x14.deft.StartContainerH\x00R\x05start\x12)\n" +
	"\x04stop\x18\x04 \x01(\v2\x13.deft.StopContainerH\x00R\x04stop\x12/\n" +
	"\x06remove\x18\x05 \x01(\v2\x15.deft.RemoveContainerH\x00R\x06removeB\b\n" +
	"\x06action\";\n" +
	"\x0fCreateContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\" \n" +
	"\x0eStartContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rStopContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fRemoveContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2G\n" +
	"\fAgentService\x127\n" +
	"\aConnect\x12\x12.deft.AgentMessage\x1a\x12.deft.PanelCommand\"\x00(\x010\x01B Z\x1egithub.com/lucasile/deft/internal/protob\x06proto3"

var (
	file_proto_agent_proto_rawDescOnce sync.Once
	file_proto_agent_proto_rawDescData []byte
)

func file_proto_agent_proto_rawDescGZIP() []byte {
	file_proto_agent_proto_rawDescOnce.Do(func() {
		file_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)))
	})
	return file_proto_agent_proto_rawDescData
}

var file_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),    // 0: deft.AgentMessage
	(*Heartbeat)(nil),       // 1: deft.Heartbeat
	(*CommandResult)(nil),   // 2: deft.CommandResult
	(*StatsUpdate)(nil),     // 3: deft.StatsUpdate
	(*PanelCommand)(nil),    // 4: deft.PanelCommand
	(*CreateContainer)(nil), // 5: deft.CreateContainer
	(*StartContainer)(nil),  // 6: deft.StartContainer
	(*StopContainer)(nil),   // 7: deft.StopContainer
	(*RemoveContainer)(nil), // 8: deft.RemoveContainer
}
var file_proto_agent_proto_depIdxs = []int32{
	1, // 0: deft.AgentMessage.heartbeat:type_name -> deft.Heartbeat
	2, // 1: deft.AgentMessage.result:type_name -> deft.CommandResult
	3, // 2: deft.AgentMessage.stats:type_name -> deft.StatsUpdate
	5, // 3: deft.PanelCommand.create:type_name -> deft.CreateContainer
	6, // 4: deft.PanelCommand.start:type_name -> deft.StartContainer
	7, // 5: deft.PanelCommand.stop:type_name -> deft.StopContainer
	8, // 6: deft.PanelCommand.remove:type_name -> deft.RemoveContainer
	0, // 7: deft.AgentService.Connect:input_type -> deft.AgentMessage
	4, // 8: deft.AgentService.Connect:output_type -> deft.PanelCommand
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_proto_agent_proto_init() }
func file_proto_agent_proto_init() {
	if File_proto_agent_proto != nil {
		return
	}
	file_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Stats)(nil),
	}
	file_proto_agent_proto_msgTypes[4].OneofWrappers = []any{
		(*PanelCommand_Create)(nil),
		(*PanelCommand_Start)(nil),
		(*PanelCommand_Stop)(nil),
		(*PanelCommand_Remove)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_agent_proto_rawDesc), len(file_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_agent_proto_goTypes,
		DependencyIndexes: file_proto_agent_proto_depIdxs,
		MessageInfos:      file_proto_agent_proto_msgTypes,
	}.Build()
	File_proto_agent_proto = out.File
	file_proto_agent_proto_goTypes = nil
	file_proto_agent_proto_depIdxs = nil
}
