// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v4.25.1
// source: internal/proto/agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*AgentMessage_Heartbeat
	//	*AgentMessage_Result
	//	*AgentMessage_Stats
	//	*AgentMessage_Inventory
	//	*AgentMessage_LogChunk
	Content       isAgentMessage_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_internal_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AgentMessage) GetContent() isAgentMessage_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *AgentMessage) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentMessage) GetResult() *CommandResult {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Result); ok {
			return x.Result
		}
	}
	return nil
}

func (x *AgentMessage) GetStats() *StatsUpdate {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Stats); ok {
			return x.Stats
		}
	}
	return nil
}

func (x *AgentMessage) GetInventory() *ContainerInventory {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_Inventory); ok {
			return x.Inventory
		}
	}
	return nil
}

func (x *AgentMessage) GetLogChunk() *LogChunk {
	if x != nil {
		if x, ok := x.Content.(*AgentMessage_LogChunk); ok {
			return x.LogChunk
		}
	}
	return nil
}

type isAgentMessage_Content interface {
	isAgentMessage_Content()
}

type AgentMessage_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentMessage_Result struct {
	Result *CommandResult `protobuf:"bytes,3,opt,name=result,proto3,oneof"`
}

type AgentMessage_Stats struct {
	Stats *StatsUpdate `protobuf:"bytes,4,opt,name=stats,proto3,oneof"`
}

type AgentMessage_Inventory struct {
	Inventory *ContainerInventory `protobuf:"bytes,5,opt,name=inventory,proto3,oneof"`
}

type AgentMessage_LogChunk struct {
	LogChunk *LogChunk `protobuf:"bytes,6,opt,name=log_chunk,json=logChunk,proto3,oneof"`
}

func (*AgentMessage_Heartbeat) isAgentMessage_Content() {}

func (*AgentMessage_Result) isAgentMessage_Content() {}

func (*AgentMessage_Stats) isAgentMessage_Content() {}

func (*AgentMessage_Inventory) isAgentMessage_Content() {}

func (*AgentMessage_LogChunk) isAgentMessage_Content() {}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_internal_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Heartbeat) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CommandResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommandId     string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandResult) Reset() {
	*x = CommandResult{}
	mi := &file_internal_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandResult) ProtoMessage() {}

func (x *CommandResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandResult.ProtoReflect.Descriptor instead.
func (*CommandResult) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *CommandResult) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *CommandResult) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CommandResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatsUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContainerId   string                 `protobuf:"bytes,1,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	CpuPercent    float64                `protobuf:"fixed64,2,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemoryBytes   uint64                 `protobuf:"varint,3,opt,name=memory_bytes,json=memoryBytes,proto3" json:"memory_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsUpdate) Reset() {
	*x = StatsUpdate{}
	mi := &file_internal_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsUpdate) ProtoMessage() {}

func (x *StatsUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsUpdate.ProtoReflect.Descriptor instead.
func (*StatsUpdate) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *StatsUpdate) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *StatsUpdate) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *StatsUpdate) GetMemoryBytes() uint64 {
	if x != nil {
		return x.MemoryBytes
	}
	return 0
}

type ContainerInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Containers    []*ContainerSummary    `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerInventory) Reset() {
	*x = ContainerInventory{}
	mi := &file_internal_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInventory) ProtoMessage() {}

func (x *ContainerInventory) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInventory.ProtoReflect.Descriptor instead.
func (*ContainerInventory) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ContainerInventory) GetContainers() []*ContainerSummary {
	if x != nil {
		return x.Containers
	}
	return nil
}

type ContainerSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ResourceId    string                 `protobuf:"bytes,5,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContainerSummary) Reset() {
	*x = ContainerSummary{}
	mi := &file_internal_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContainerSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerSummary) ProtoMessage() {}

func (x *ContainerSummary) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerSummary.ProtoReflect.Descriptor instead.
func (*ContainerSummary) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ContainerSummary) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ContainerSummary) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ContainerSummary) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type LogChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	ContainerId   string                 `protobuf:"bytes,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Eof           bool                   `protobuf:"varint,4,opt,name=eof,proto3" json:"eof,omitempty"`
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogChunk) Reset() {
	*x = LogChunk{}
	mi := &file_internal_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogChunk) ProtoMessage() {}

func (x *LogChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogChunk.ProtoReflect.Descriptor instead.
func (*LogChunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *LogChunk) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *LogChunk) GetContainerId() string {
	if x != nil {
		return x.ContainerId
	}
	return ""
}

func (x *LogChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogChunk) GetEof() bool {
	if x != nil {
		return x.Eof
	}
	return false
}

func (x *LogChunk) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PanelCommand struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	CommandId string                 `protobuf:"bytes,1,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	// Types that are valid to be assigned to Action:
	//
	//	*PanelCommand_Create
	//	*PanelCommand_Start
	//	*PanelCommand_Stop
	//	*PanelCommand_Remove
	//	*PanelCommand_Shutdown
	//	*PanelCommand_Logs
	//	*PanelCommand_FollowLogs
	//	*PanelCommand_CancelLogs
	Action        isPanelCommand_Action `protobuf_oneof:"action"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelCommand) Reset() {
	*x = PanelCommand{}
	mi := &file_internal_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelCommand) ProtoMessage() {}

func (x *PanelCommand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelCommand.ProtoReflect.Descriptor instead.
func (*PanelCommand) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *PanelCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *PanelCommand) GetAction() isPanelCommand_Action {
	if x != nil {
		return x.Action
	}
	return nil
}

func (x *PanelCommand) GetCreate() *CreateContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Create); ok {
			return x.Create
		}
	}
	return nil
}

func (x *PanelCommand) GetStart() *StartContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Start); ok {
			return x.Start
		}
	}
	return nil
}

func (x *PanelCommand) GetStop() *StopContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Stop); ok {
			return x.Stop
		}
	}
	return nil
}

func (x *PanelCommand) GetRemove() *RemoveContainer {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Remove); ok {
			return x.Remove
		}
	}
	return nil
}

func (x *PanelCommand) GetShutdown() *ShutdownAgent {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Shutdown); ok {
			return x.Shutdown
		}
	}
	return nil
}

func (x *PanelCommand) GetLogs() *GetContainerLogs {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_Logs); ok {
			return x.Logs
		}
	}
	return nil
}

func (x *PanelCommand) GetFollowLogs() *FollowContainerLogs {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_FollowLogs); ok {
			return x.FollowLogs
		}
	}
	return nil
}

func (x *PanelCommand) GetCancelLogs() *CancelLogStream {
	if x != nil {
		if x, ok := x.Action.(*PanelCommand_CancelLogs); ok {
			return x.CancelLogs
		}
	}
	return nil
}

type isPanelCommand_Action interface {
	isPanelCommand_Action()
}

type PanelCommand_Create struct {
	Create *CreateContainer `protobuf:"bytes,2,opt,name=create,proto3,oneof"`
}

type PanelCommand_Start struct {
	Start *StartContainer `protobuf:"bytes,3,opt,name=start,proto3,oneof"`
}

type PanelCommand_Stop struct {
	Stop *StopContainer `protobuf:"bytes,4,opt,name=stop,proto3,oneof"`
}

type PanelCommand_Remove struct {
	Remove *RemoveContainer `protobuf:"bytes,5,opt,name=remove,proto3,oneof"`
}

type PanelCommand_Shutdown struct {
	Shutdown *ShutdownAgent `protobuf:"bytes,6,opt,name=shutdown,proto3,oneof"`
}

type PanelCommand_Logs struct {
	Logs *GetContainerLogs `protobuf:"bytes,7,opt,name=logs,proto3,oneof"`
}

type PanelCommand_FollowLogs struct {
	FollowLogs *FollowContainerLogs `protobuf:"bytes,8,opt,name=follow_logs,json=followLogs,proto3,oneof"`
}

type PanelCommand_CancelLogs struct {
	CancelLogs *CancelLogStream `protobuf:"bytes,9,opt,name=cancel_logs,json=cancelLogs,proto3,oneof"`
}

func (*PanelCommand_Create) isPanelCommand_Action() {}

func (*PanelCommand_Start) isPanelCommand_Action() {}

func (*PanelCommand_Stop) isPanelCommand_Action() {}

func (*PanelCommand_Remove) isPanelCommand_Action() {}

func (*PanelCommand_Shutdown) isPanelCommand_Action() {}

func (*PanelCommand_Logs) isPanelCommand_Action() {}

func (*PanelCommand_FollowLogs) isPanelCommand_Action() {}

func (*PanelCommand_CancelLogs) isPanelCommand_Action() {}

type CreateContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	DisplayName   string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	ResourceId    string                 `protobuf:"bytes,4,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Ports         []*PortMapping         `protobuf:"bytes,5,rep,name=ports,proto3" json:"ports,omitempty"`
	Env           []*EnvVar              `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty"`
	Volumes       []*VolumeMount         `protobuf:"bytes,7,rep,name=volumes,proto3" json:"volumes,omitempty"`
	RestartPolicy string                 `protobuf:"bytes,8,opt,name=restart_policy,json=restartPolicy,proto3" json:"restart_policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateContainer) Reset() {
	*x = CreateContainer{}
	mi := &file_internal_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateContainer) ProtoMessage() {}

func (x *CreateContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateContainer.ProtoReflect.Descriptor instead.
func (*CreateContainer) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *CreateContainer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateContainer) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *CreateContainer) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *CreateContainer) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *CreateContainer) GetPorts() []*PortMapping {
	if x != nil {
		return x.Ports
	}
	return nil
}

func (x *CreateContainer) GetEnv() []*EnvVar {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *CreateContainer) GetVolumes() []*VolumeMount {
	if x != nil {
		return x.Volumes
	}
	return nil
}

func (x *CreateContainer) GetRestartPolicy() string {
	if x != nil {
		return x.RestartPolicy
	}
	return ""
}

type PortMapping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPort      uint32                 `protobuf:"varint,1,opt,name=host_port,json=hostPort,proto3" json:"host_port,omitempty"`
	ContainerPort uint32                 `protobuf:"varint,2,opt,name=container_port,json=containerPort,proto3" json:"container_port,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PortMapping) Reset() {
	*x = PortMapping{}
	mi := &file_internal_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortMapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortMapping) ProtoMessage() {}

func (x *PortMapping) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PortMapping.ProtoReflect.Descriptor instead.
func (*PortMapping) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *PortMapping) GetHostPort() uint32 {
	if x != nil {
		return x.HostPort
	}
	return 0
}

func (x *PortMapping) GetContainerPort() uint32 {
	if x != nil {
		return x.ContainerPort
	}
	return 0
}

func (x *PortMapping) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type EnvVar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnvVar) Reset() {
	*x = EnvVar{}
	mi := &file_internal_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnvVar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnvVar) ProtoMessage() {}

func (x *EnvVar) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnvVar.ProtoReflect.Descriptor instead.
func (*EnvVar) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *EnvVar) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *EnvVar) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VolumeMount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HostPath      string                 `protobuf:"bytes,1,opt,name=host_path,json=hostPath,proto3" json:"host_path,omitempty"`
	ContainerPath string                 `protobuf:"bytes,2,opt,name=container_path,json=containerPath,proto3" json:"container_path,omitempty"`
	ReadOnly      bool                   `protobuf:"varint,3,opt,name=read_only,json=readOnly,proto3" json:"read_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VolumeMount) Reset() {
	*x = VolumeMount{}
	mi := &file_internal_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VolumeMount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VolumeMount) ProtoMessage() {}

func (x *VolumeMount) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VolumeMount.ProtoReflect.Descriptor instead.
func (*VolumeMount) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *VolumeMount) GetHostPath() string {
	if x != nil {
		return x.HostPath
	}
	return ""
}

func (x *VolumeMount) GetContainerPath() string {
	if x != nil {
		return x.ContainerPath
	}
	return ""
}

func (x *VolumeMount) GetReadOnly() bool {
	if x != nil {
		return x.ReadOnly
	}
	return false
}

type StartContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartContainer) Reset() {
	*x = StartContainer{}
	mi := &file_internal_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartContainer) ProtoMessage() {}

func (x *StartContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartContainer.ProtoReflect.Descriptor instead.
func (*StartContainer) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *StartContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type StopContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopContainer) Reset() {
	*x = StopContainer{}
	mi := &file_internal_proto_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopContainer) ProtoMessage() {}

func (x *StopContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopContainer.ProtoReflect.Descriptor instead.
func (*StopContainer) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{13}
}

func (x *StopContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RemoveContainer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveContainer) Reset() {
	*x = RemoveContainer{}
	mi := &file_internal_proto_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveContainer) ProtoMessage() {}

func (x *RemoveContainer) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveContainer.ProtoReflect.Descriptor instead.
func (*RemoveContainer) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveContainer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ShutdownAgent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownAgent) Reset() {
	*x = ShutdownAgent{}
	mi := &file_internal_proto_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownAgent) ProtoMessage() {}

func (x *ShutdownAgent) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownAgent.ProtoReflect.Descriptor instead.
func (*ShutdownAgent) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{15}
}

type GetContainerLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContainerLogs) Reset() {
	*x = GetContainerLogs{}
	mi := &file_internal_proto_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContainerLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContainerLogs) ProtoMessage() {}

func (x *GetContainerLogs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContainerLogs.ProtoReflect.Descriptor instead.
func (*GetContainerLogs) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{16}
}

func (x *GetContainerLogs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetContainerLogs) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

type FollowContainerLogs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TailLines     int32                  `protobuf:"varint,2,opt,name=tail_lines,json=tailLines,proto3" json:"tail_lines,omitempty"`
	StreamId      string                 `protobuf:"bytes,3,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FollowContainerLogs) Reset() {
	*x = FollowContainerLogs{}
	mi := &file_internal_proto_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FollowContainerLogs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FollowContainerLogs) ProtoMessage() {}

func (x *FollowContainerLogs) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FollowContainerLogs.ProtoReflect.Descriptor instead.
func (*FollowContainerLogs) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{17}
}

func (x *FollowContainerLogs) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *FollowContainerLogs) GetTailLines() int32 {
	if x != nil {
		return x.TailLines
	}
	return 0
}

func (x *FollowContainerLogs) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type CancelLogStream struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelLogStream) Reset() {
	*x = CancelLogStream{}
	mi := &file_internal_proto_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelLogStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelLogStream) ProtoMessage() {}

func (x *CancelLogStream) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelLogStream.ProtoReflect.Descriptor instead.
func (*CancelLogStream) Descriptor() ([]byte, []int) {
	return file_internal_proto_agent_proto_rawDescGZIP(), []int{18}
}

func (x *CancelLogStream) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

var File_internal_proto_agent_proto protoreflect.FileDescriptor

const file_internal_proto_agent_proto_rawDesc = "" +
	"\n" +
	"\x1ainternal/proto/agent.proto\x12\x04deft\"\xa6\x02\n" +
	"\fAgentMessage\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12/\n" +
	"\theartbeat\x18\x02 \x01(\v2\x0f.deft.HeartbeatH\x00R\theartbeat\x12-\n" +
	"\x06result\x18\x03 \x01(\v2\x13.deft.CommandResultH\x00R\x06result\x12)\n" +
	"\x05stats\x18\x04 \x01(\v2\x11.deft.StatsUpdateH\x00R\x05stats\x128\n" +
	"\tinventory\x18\x05 \x01(\v2\x18.deft.ContainerInventoryH\x00R\tinventory\x12-\n" +
	"\tlog_chunk\x18\x06 \x01(\v2\x0e.deft.LogChunkH\x00R\blogChunkB\t\n" +
	"\acontent\")\n" +
	"\tHeartbeat\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\"b\n" +
	"\rCommandResult\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\vStatsUpdate\x12!\n" +
	"\fcontainer_id\x18\x01 \x01(\tR\vcontainerId\x12\x1f\n" +
	"\vcpu_percent\x18\x02 \x01(\x01R\n" +
	"cpuPercent\x12!\n" +
	"\fmemory_bytes\x18\x03 \x01(\x04R\vmemoryBytes\"L\n" +
	"\x12ContainerInventory\x126\n" +
	"\n" +
	"containers\x18\x01 \x03(\v2\x16.deft.ContainerSummaryR\n" +
	"containers\"\x85\x01\n" +
	"\x10ContainerSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x03 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x1f\n" +
	"\vresource_id\x18\x05 \x01(\tR\n" +
	"resourceId\"\x86\x01\n" +
	"\bLogChunk\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\tR\vcontainerId\x12\x12\n" +
	"\x04data\x18\x03 \x01(\fR\x04data\x12\x10\n" +
	"\x03eof\x18\x04 \x01(\bR\x03eof\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"\xcb\x03\n" +
	"\fPanelCommand\x12\x1d\n" +
	"\n" +
	"command_id\x18\x01 \x01(\tR\tcommandId\x12/\n" +
	"\x06create\x18\x02 \x01(\v2\x15.deft.CreateContainerH\x00R\x06create\x12,\n" +
	"\x05start\x18\x03 \x01(\v2\x14.deft.StartContainerH\x00R\x05start\x12)\n" +
	"\x04stop\x18\x04 \x01(\v2\x13.deft.StopContainerH\x00R\x04stop\x12/\n" +
	"\x06remove\x18\x05 \x01(\v2\x15.deft.RemoveContainerH\x00R\x06remove\x121\n" +
	"\bshutdown\x18\x06 \x01(\v2\x13.deft.ShutdownAgentH\x00R\bshutdown\x12,\n" +
	"\x04logs\x18\a \x01(\v2\x16.deft.GetContainerLogsH\x00R\x04logs\x12<\n" +
	"\vfollow_logs\x18\b \x01(\v2\x19.deft.FollowContainerLogsH\x00R\n" +
	"followLogs\x128\n" +
	"\vcancel_logs\x18\t \x01(\v2\x15.deft.CancelLogStreamH\x00R\n" +
	"cancelLogsB\b\n" +
	"\x06action\"\x9c\x02\n" +
	"\x0fCreateContainer\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12\x1f\n" +
	"\vresource_id\x18\x04 \x01(\tR\n" +
	"resourceId\x12'\n" +
	"\x05ports\x18\x05 \x03(\v2\x11.deft.PortMappingR\x05ports\x12\x1e\n" +
	"\x03env\x18\x06 \x03(\v2\f.deft.EnvVarR\x03env\x12+\n" +
	"\avolumes\x18\a \x03(\v2\x11.deft.VolumeMountR\avolumes\x12%\n" +
	"\x0erestart_policy\x18\b \x01(\tR\rrestartPolicy\"m\n" +
	"\vPortMapping\x12\x1b\n" +
	"\thost_port\x18\x01 \x01(\rR\bhostPort\x12%\n" +
	"\x0econtainer_port\x18\x02 \x01(\rR\rcontainerPort\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"0\n" +
	"\x06EnvVar\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"n\n" +
	"\vVolumeMount\x12\x1b\n" +
	"\thost_path\x18\x01 \x01(\tR\bhostPath\x12%\n" +
	"\x0econtainer_path\x18\x02 \x01(\tR\rcontainerPath\x12\x1b\n" +
	"\tread_only\x18\x03 \x01(\bR\breadOnly\" \n" +
	"\x0eStartContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rStopContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"!\n" +
	"\x0fRemoveContainer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x0f\n" +
	"\rShutdownAgent\"A\n" +
	"\x10GetContainerLogs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\"a\n" +
	"\x13FollowContainerLogs\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"tail_lines\x18\x02 \x01(\x05R\ttailLines\x12\x1b\n" +
	"\tstream_id\x18\x03 \x01(\tR\bstreamId\".\n" +
	"\x0fCancelLogStream\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId2G\n" +
	"\fAgentService\x127\n" +
	"\aConnect\x12\x12.deft.AgentMessage\x1a\x12.deft.PanelCommand\"\x00(\x010\x01B)Z'github.com/lucasile/deft/internal/protob\x06proto3"

var (
	file_internal_proto_agent_proto_rawDescOnce sync.Once
	file_internal_proto_agent_proto_rawDescData []byte
)

func file_internal_proto_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_agent_proto_rawDesc), len(file_internal_proto_agent_proto_rawDesc)))
	})
	return file_internal_proto_agent_proto_rawDescData
}

var file_internal_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_proto_agent_proto_goTypes = []any{
	(*AgentMessage)(nil),        // 0: deft.AgentMessage
	(*Heartbeat)(nil),           // 1: deft.Heartbeat
	(*CommandResult)(nil),       // 2: deft.CommandResult
	(*StatsUpdate)(nil),         // 3: deft.StatsUpdate
	(*ContainerInventory)(nil),  // 4: deft.ContainerInventory
	(*ContainerSummary)(nil),    // 5: deft.ContainerSummary
	(*LogChunk)(nil),            // 6: deft.LogChunk
	(*PanelCommand)(nil),        // 7: deft.PanelCommand
	(*CreateContainer)(nil),     // 8: deft.CreateContainer
	(*PortMapping)(nil),         // 9: deft.PortMapping
	(*EnvVar)(nil),              // 10: deft.EnvVar
	(*VolumeMount)(nil),         // 11: deft.VolumeMount
	(*StartContainer)(nil),      // 12: deft.StartContainer
	(*StopContainer)(nil),       // 13: deft.StopContainer
	(*RemoveContainer)(nil),     // 14: deft.RemoveContainer
	(*ShutdownAgent)(nil),       // 15: deft.ShutdownAgent
	(*GetContainerLogs)(nil),    // 16: deft.GetContainerLogs
	(*FollowContainerLogs)(nil), // 17: deft.FollowContainerLogs
	(*CancelLogStream)(nil),     // 18: deft.CancelLogStream
}
var file_internal_proto_agent_proto_depIdxs = []int32{
	1,  // 0: deft.AgentMessage.heartbeat:type_name -> deft.Heartbeat
	2,  // 1: deft.AgentMessage.result:type_name -> deft.CommandResult
	3,  // 2: deft.AgentMessage.stats:type_name -> deft.StatsUpdate
	4,  // 3: deft.AgentMessage.inventory:type_name -> deft.ContainerInventory
	6,  // 4: deft.AgentMessage.log_chunk:type_name -> deft.LogChunk
	5,  // 5: deft.ContainerInventory.containers:type_name -> deft.ContainerSummary
	8,  // 6: deft.PanelCommand.create:type_name -> deft.CreateContainer
	12, // 7: deft.PanelCommand.start:type_name -> deft.StartContainer
	13, // 8: deft.PanelCommand.stop:type_name -> deft.StopContainer
	14, // 9: deft.PanelCommand.remove:type_name -> deft.RemoveContainer
	15, // 10: deft.PanelCommand.shutdown:type_name -> deft.ShutdownAgent
	16, // 11: deft.PanelCommand.logs:type_name -> deft.GetContainerLogs
	17, // 12: deft.PanelCommand.follow_logs:type_name -> deft.FollowContainerLogs
	18, // 13: deft.PanelCommand.cancel_logs:type_name -> deft.CancelLogStream
	9,  // 14: deft.CreateContainer.ports:type_name -> deft.PortMapping
	10, // 15: deft.CreateContainer.env:type_name -> deft.EnvVar
	11, // 16: deft.CreateContainer.volumes:type_name -> deft.VolumeMount
	0,  // 17: deft.AgentService.Connect:input_type -> deft.AgentMessage
	7,  // 18: deft.AgentService.Connect:output_type -> deft.PanelCommand
	18, // [18:19] is the sub-list for method output_type
	17, // [17:18] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_internal_proto_agent_proto_init() }
func file_internal_proto_agent_proto_init() {
	if File_internal_proto_agent_proto != nil {
		return
	}
	file_internal_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Heartbeat)(nil),
		(*AgentMessage_Result)(nil),
		(*AgentMessage_Stats)(nil),
		(*AgentMessage_Inventory)(nil),
		(*AgentMessage_LogChunk)(nil),
	}
	file_internal_proto_agent_proto_msgTypes[7].OneofWrappers = []any{
		(*PanelCommand_Create)(nil),
		(*PanelCommand_Start)(nil),
		(*PanelCommand_Stop)(nil),
		(*PanelCommand_Remove)(nil),
		(*PanelCommand_Shutdown)(nil),
		(*PanelCommand_Logs)(nil),
		(*PanelCommand_FollowLogs)(nil),
		(*PanelCommand_CancelLogs)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_agent_proto_rawDesc), len(file_internal_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_agent_proto_depIdxs,
		MessageInfos:      file_internal_proto_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_agent_proto = out.File
	file_internal_proto_agent_proto_goTypes = nil
	file_internal_proto_agent_proto_depIdxs = nil
}
